# Generated by Django 2.2.2 on 2019-12-21 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.URLField(null=True, verbose_name='Server url')),
                ('address_1', models.CharField(max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(default='Düsseldorf', max_length=64, verbose_name='city')),
                ('Counrty', models.CharField(default='Germany', max_length=64, verbose_name='country')),
                ('state', models.CharField(default='', max_length=64, verbose_name='state')),
                ('zip_code', models.CharField(default='43701', max_length=5, verbose_name='zip code')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='with country code (eg. +48)', max_length=128, null=True, region=None, verbose_name='Mobile')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='clients.Client', verbose_name='Sales Man')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
