# Generated by Django 2.2.2 on 2019-12-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Counrty',
        ),
        migrations.AddField(
            model_name='profile',
            name='counrty',
            field=models.CharField(default='Germany', max_length=64, verbose_name='Country'),
        ),
    ]
