# Generated by Django 2.2.2 on 2019-12-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191222_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='counrty',
            new_name='country',
        ),
    ]
