# Generated by Django 2.2.2 on 2019-12-21 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('invoice_no', models.UUIDField(default=uuid.uuid4, verbose_name='Invoice Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('terms', models.TextField(blank=True, default='')),
                ('du_date', models.DateTimeField(auto_now_add=True, verbose_name='Du Date')),
                ('invoice_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Invoice Date')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name Of Item')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, default='')),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.Invoice', verbose_name='Invoices')),
            ],
        ),
    ]
