# Generated by Django 2.2.2 on 2019-12-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_invoice'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='clients',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='clients_invoices', to='clients.Client', verbose_name='Invoice Client '),
            preserve_default=False,
        ),
    ]
