# Generated by Django 2.2.2 on 2019-12-21 20:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('server_url', models.URLField(null=True, verbose_name='Server url')),
                ('address_1', models.CharField(max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(default='Düsseldorf', max_length=64, verbose_name='city')),
                ('Counrty', models.CharField(default='Germany', max_length=64, verbose_name='country')),
                ('state', models.CharField(default='', max_length=64, verbose_name='state')),
                ('zip_code', models.CharField(default='43701', max_length=5, verbose_name='zip code')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='with country code (eg. +48)', max_length=128, null=True, region=None, verbose_name='Mobile')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_invoices', to='invoices.Invoice', verbose_name='Invoices')),
            ],
        ),
    ]
