# Generated by Django 2.2.2 on 2019-12-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='invoice',
        ),
    ]
